### ISSUE TITLE
Keep the count of reports generated

### ISSUE THREAD

**Issue by adrien-nf** [nathangobinet/git-report-api#3]

**Comment by nathangobinet** [comment]
Just for stats right ?
Actually we dont have database, so i can easily have a local variable that counts the generated reports but when the instance will be closed it will be reseted to 0.

**Comment by adrien-nf** [comment]
Just for stats and fun, indeed.
The date could be saved in a simply txt file on server close, and read up again on server starting. What do you think of that?

**Comment by nathangobinet** [comment]
Yup could work indeed, i have to check how to trigger a close event

**Comment by nathangobinet** [comment]
Added to status
https://flash.vps.webdock.cloud/api/status
It's incremented when the user send commit to the server.
You can close the issue if it's good for you.
